# Site settings
title: "Tulip Holding"
description: "Specialists in Light Industrial Real Estate"
email: "holl@tulipholding.cz"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tulipholding.cz" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate

# Navigation
header_pages:
  - about.md
  - services.md
  - contact.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
